// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0hhH74kAUq5B-quItQjG5yoTzBq5j4A',
    appId: '1:227571865273:web:f78ef58286b7eabe216d68',
    messagingSenderId: '227571865273',
    projectId: 'tamredak-c2fb9',
    authDomain: 'tamredak-c2fb9.firebaseapp.com',
    storageBucket: 'tamredak-c2fb9.appspot.com',
    measurementId: 'G-2X0YG8V3X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqim561-nFyeE_1Ld0Ao5z6Maejx_RMA',
    appId: '1:227571865273:android:eb8adde0e7b0013d216d68',
    messagingSenderId: '227571865273',
    projectId: 'tamredak-c2fb9',
    storageBucket: 'tamredak-c2fb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmbncHmYKzMERKwbe_HX-J1LHTcXheVs',
    appId: '1:227571865273:ios:e3adc9f9b5366ed2216d68',
    messagingSenderId: '227571865273',
    projectId: 'tamredak-c2fb9',
    storageBucket: 'tamredak-c2fb9.appspot.com',
    iosBundleId: 'com.example.tamredak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmbncHmYKzMERKwbe_HX-J1LHTcXheVs',
    appId: '1:227571865273:ios:a4b061353e02c8e4216d68',
    messagingSenderId: '227571865273',
    projectId: 'tamredak-c2fb9',
    storageBucket: 'tamredak-c2fb9.appspot.com',
    iosBundleId: 'com.example.tamredak.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqim561-nFyeE_1Ld0Ao5z6Maejx_RMA',
    appId: '1:227571865273:windows:eb8adde0e7b0013d216d68',
    messagingSenderId: '227571865273',
    projectId: 'tamredak-c2fb9',
    storageBucket: 'tamredak-c2fb9.appspot.com',
  );
}
